// ── Centralized badge definitions ─────────────────────────────────────────────
// Single source of truth used by profile, public profile, and the badge engine

export const BADGES = [
  // ── STRENGTH ──────────────────────────────────────────────────────────────
  { id:"1k-club",        emoji:"🏋️", label:"1,000 lb Club",      desc:"Squat + Bench + Deadlift ≥ 1,000 lbs",   category:"strength" },
  { id:"heavy-lifter",   emoji:"💪", label:"Heavy Lifter",        desc:"Logged a single lift over 300 lbs",       category:"strength" },
  { id:"pb-crusher",     emoji:"🚀", label:"PB Crusher",          desc:"Set 5 personal bests in one month",       category:"strength" },
  { id:"iron-maiden",    emoji:"⚒️", label:"Iron Maiden",         desc:"Deadlifted 2x your bodyweight",           category:"strength" },
  { id:"bench-200",      emoji:"🪨", label:"200 Club",            desc:"Bench pressed 200 lbs",                   category:"strength" },
  { id:"squat-300",      emoji:"🦵", label:"Squat King",          desc:"Back squatted 300 lbs",                   category:"strength" },
  { id:"deadlift-400",   emoji:"⚓", label:"Deadlift Beast",      desc:"Deadlifted 400 lbs",                      category:"strength" },
  { id:"overhead-bw",    emoji:"🙌", label:"Overhead Master",     desc:"Overhead pressed your bodyweight",        category:"strength" },
  { id:"weighted-pullup",emoji:"🧲", label:"Weighted Pull-Up",    desc:"Completed a pull-up with added weight",   category:"strength" },
  { id:"kettlebell-king",emoji:"🔔", label:"Kettlebell King",     desc:"Completed 100 kettlebell swings in a row",category:"strength" },
  { id:"1rm-pr",         emoji:"🎯", label:"One Rep Max",         desc:"Hit a 1RM personal record",               category:"strength" },
  { id:"powerlifter",    emoji:"🏆", label:"Powerlifter",         desc:"Competed in a powerlifting meet",         category:"strength" },
  // Lifting milestones (auto-awarded)
  { id:"first-lift",     emoji:"🏗️", label:"First Lift",         desc:"Logged your first lifting session",       category:"strength" },
  { id:"lifts-10",       emoji:"💪", label:"10 Sessions",         desc:"Logged 10 lifting sessions",              category:"strength" },
  { id:"lifts-25",       emoji:"🔩", label:"Iron Regular",        desc:"Logged 25 lifting sessions",              category:"strength" },
  { id:"lifts-50",       emoji:"⚡", label:"Iron Veteran",        desc:"Logged 50 lifting sessions",              category:"strength" },
  { id:"lifts-100",      emoji:"👑", label:"Iron Legend",         desc:"Logged 100 lifting sessions",             category:"strength" },
  { id:"lifts-200",      emoji:"💎", label:"Iron Dynasty",        desc:"Logged 200 lifting sessions",             category:"strength" },
  { id:"lifts-500",      emoji:"🗿", label:"Iron Immortal",       desc:"Logged 500 lifting sessions",             category:"strength" },
  { id:"lifts-1000",     emoji:"🌋", label:"Iron God",            desc:"Logged 1,000 lifting sessions",           category:"strength" },

  // ── CARDIO ────────────────────────────────────────────────────────────────
  { id:"marathon",       emoji:"🏅", label:"Marathon Runner",     desc:"Completed a 26.2 mile run",               category:"cardio" },
  { id:"6min-mile",      emoji:"⚡", label:"6 Minute Mile",       desc:"Ran a mile in under 6 minutes",           category:"cardio" },
  { id:"half-marathon",  emoji:"🏃", label:"Half Marathoner",     desc:"Completed a 13.1 mile run",               category:"cardio" },
  { id:"5k",             emoji:"🎽", label:"5K Runner",           desc:"Completed your first 5K",                 category:"cardio" },
  { id:"10k",            emoji:"🏁", label:"10K Runner",          desc:"Completed your first 10K",                category:"cardio" },
  { id:"ultra",          emoji:"🌄", label:"Ultra Runner",        desc:"Completed an ultra marathon (50K+)",      category:"cardio" },
  { id:"century-ride",   emoji:"🚴", label:"Century Rider",       desc:"Cycled 100 miles in one ride",            category:"cardio" },
  { id:"triathlon",      emoji:"🏊", label:"Triathlete",          desc:"Completed a triathlon",                   category:"cardio" },
  { id:"ironman",        emoji:"🦾", label:"Ironman",             desc:"Completed a full Ironman",                category:"cardio" },
  { id:"swim-mile",      emoji:"🌊", label:"Open Water Swimmer",  desc:"Swam 1 mile in open water",              category:"cardio" },
  { id:"rowing-10k",     emoji:"🚣", label:"Rower",               desc:"Rowed 10,000 meters in one session",      category:"cardio" },
  // Running milestones (auto-awarded)
  { id:"first-run",      emoji:"👟", label:"First Run",           desc:"Logged your first run",                   category:"cardio" },
  { id:"runs-5",         emoji:"🏃", label:"5 Runs",              desc:"Logged 5 runs",                           category:"cardio" },
  { id:"runs-20",        emoji:"🌟", label:"20 Runs",             desc:"Logged 20 runs",                          category:"cardio" },
  { id:"runs-50",        emoji:"🔥", label:"50 Runs",             desc:"Logged 50 runs",                          category:"cardio" },
  { id:"runs-100",       emoji:"🏆", label:"100 Run Club",        desc:"Logged 100 runs",                         category:"cardio" },
  { id:"runs-200",       emoji:"💎", label:"200 Run Society",     desc:"Logged 200 runs",                         category:"cardio" },
  { id:"runs-500",       emoji:"🗿", label:"500 Run Immortal",    desc:"Logged 500 runs",                         category:"cardio" },
  { id:"runs-1000",      emoji:"🌋", label:"1,000 Run Legend",    desc:"Logged 1,000 runs",                       category:"cardio" },

  // ── CONSISTENCY ───────────────────────────────────────────────────────────
  { id:"7day-streak",    emoji:"🔥", label:"7 Day Streak",        desc:"Logged activity 7 days in a row",         category:"consistency" },
  { id:"early-bird",     emoji:"🌅", label:"Early Bird",          desc:"Logged 5 workouts before 7am",            category:"consistency" },
  { id:"centurion",      emoji:"💯", label:"Centurion",           desc:"Logged 100 workouts total",               category:"consistency" },
  { id:"30day-streak",   emoji:"🗓️", label:"30 Day Streak",      desc:"Logged activity 30 days in a row",        category:"consistency" },
  { id:"90day-streak",   emoji:"💎", label:"90 Day Grind",        desc:"Logged activity 90 days in a row",        category:"consistency" },
  { id:"365day",         emoji:"🌟", label:"Year Warrior",        desc:"Logged activity 365 days in a year",      category:"consistency" },
  { id:"no-days-off",    emoji:"🚫", label:"No Days Off",         desc:"Logged at least one activity every day for 14 days", category:"consistency" },
  { id:"comeback",       emoji:"🔄", label:"Comeback Kid",        desc:"Returned to logging after a 30-day break",category:"consistency" },
  { id:"weekend-warrior",emoji:"⚔️", label:"Weekend Warrior",    desc:"Worked out every weekend for a month",    category:"consistency" },
  // Total workout milestones (auto-awarded)
  { id:"first-workout",  emoji:"🎉", label:"First Workout",       desc:"Logged your very first workout",          category:"consistency" },
  { id:"workouts-10",    emoji:"📈", label:"10 Workouts",         desc:"Logged 10 total workouts",                category:"consistency" },
  { id:"workouts-25",    emoji:"⭐", label:"25 Workouts",         desc:"Logged 25 total workouts",                category:"consistency" },
  { id:"centurion-half", emoji:"🥈", label:"50 Strong",           desc:"Logged 50 total workouts",                category:"consistency" },
  { id:"centurion-2x",   emoji:"💎", label:"200 Titan",           desc:"Logged 200 total workouts",               category:"consistency" },
  { id:"500-workouts",   emoji:"👑", label:"500 Legend",          desc:"Logged 500 total workouts",               category:"consistency" },
  { id:"1000-workouts",  emoji:"🌋", label:"1,000 Immortal",      desc:"Logged 1,000 total workouts",             category:"consistency" },

  // ── WELLNESS ──────────────────────────────────────────────────────────────
  { id:"yoga-lover",     emoji:"🧘", label:"Yoga Lover",          desc:"Logged 30 yoga sessions",                 category:"wellness" },
  { id:"yoga-queen",     emoji:"🪷", label:"Yoga Queen",          desc:"Logged 100 yoga sessions",                category:"wellness" },
  { id:"meditation-master",emoji:"🕊️",label:"Meditation Master", desc:"Logged 30 meditation sessions",           category:"wellness" },
  { id:"sleep-champ",    emoji:"😴", label:"Sleep Champion",      desc:"Logged 8+ hours of sleep 7 nights in a row",category:"wellness" },
  { id:"hydration-hero", emoji:"💧", label:"Hydration Hero",      desc:"Hit daily water goal 14 days in a row",  category:"wellness" },
  { id:"stretch-it-out", emoji:"🤸", label:"Stretch It Out",      desc:"Logged 20 stretching sessions",           category:"wellness" },
  { id:"ice-bath",       emoji:"🧊", label:"Ice Bath Club",       desc:"Took 5 ice baths or cold plunges",        category:"wellness" },
  { id:"ice-warrior",    emoji:"❄️", label:"Ice Warrior",         desc:"Completed 50 cold plunges",               category:"wellness" },
  { id:"sauna",          emoji:"🔆", label:"Sauna Regular",       desc:"Logged 10 sauna sessions",                category:"wellness" },
  { id:"sauna-30",       emoji:"🌡️", label:"Sauna Devotee",      desc:"Logged 30 sauna sessions",                category:"wellness" },
  { id:"breathwork",     emoji:"🫁", label:"Breathwork Practitioner",desc:"Completed 10 breathwork sessions",     category:"wellness" },
  { id:"breathwork-30",  emoji:"🌬️", label:"Breath Master",      desc:"Completed 30 breathwork sessions",        category:"wellness" },
  { id:"zero-alcohol",   emoji:"🫗", label:"Sober Streak",        desc:"Logged 30 alcohol-free days",             category:"wellness" },
  { id:"step-10k",       emoji:"👟", label:"10K Steps",           desc:"Hit 10,000 steps daily for 7 days",       category:"wellness" },
  { id:"step-15k",       emoji:"🦿", label:"Step Master",         desc:"Hit 15,000 steps in a single day",        category:"wellness" },
  { id:"posture",        emoji:"🪑", label:"Posture Pro",         desc:"Completed 20 posture/mobility workouts",  category:"wellness" },
  { id:"nature-walk",    emoji:"🌿", label:"Nature Walker",       desc:"Logged 10 outdoor walks",                 category:"wellness" },
  { id:"walks-50",       emoji:"🌍", label:"Wanderer",            desc:"Logged 50 walks",                         category:"wellness" },
  { id:"wellness-10",    emoji:"🌱", label:"Wellness Starter",    desc:"Logged 10 wellness activities",           category:"wellness" },
  { id:"wellness-50",    emoji:"🌳", label:"Wellness Devotee",    desc:"Logged 50 wellness activities",           category:"wellness" },
  // First-time wellness (auto-awarded)
  { id:"first-yoga",        emoji:"🧘", label:"First Yoga",       desc:"Logged your first yoga session",          category:"wellness" },
  { id:"yoga-10",           emoji:"🪷", label:"10 Yoga Sessions", desc:"Logged 10 yoga sessions",                 category:"wellness" },
  { id:"first-meditation",  emoji:"🕊️",label:"First Meditation", desc:"Logged your first meditation",            category:"wellness" },
  { id:"meditation-10",     emoji:"🧠", label:"10 Meditations",   desc:"Logged 10 meditation sessions",           category:"wellness" },
  { id:"first-cold-plunge", emoji:"🧊", label:"First Cold Plunge",desc:"Took your first cold plunge",             category:"wellness" },
  { id:"cold-plunge-20",    emoji:"💦", label:"Cold Plunge Addict",desc:"Completed 20 cold plunges",              category:"wellness" },
  { id:"first-sauna",       emoji:"🔆", label:"First Sauna",      desc:"Logged your first sauna session",         category:"wellness" },
  { id:"first-breathwork",  emoji:"🫁", label:"First Breathwork", desc:"Logged your first breathwork session",    category:"wellness" },
  { id:"first-walk",        emoji:"🌿", label:"First Walk",       desc:"Logged your first walk",                  category:"wellness" },
  { id:"first-stretch",     emoji:"🤸", label:"First Stretch",    desc:"Logged your first stretching session",    category:"wellness" },

  // ── NUTRITION ─────────────────────────────────────────────────────────────
  { id:"calorie-goals",  emoji:"🎯", label:"On Target",           desc:"Hit calorie goal 7 days in a row",        category:"nutrition" },
  { id:"protein-streak", emoji:"🥩", label:"Protein Streak",      desc:"Hit protein goal 14 days in a row",       category:"nutrition" },
  { id:"meal-prep",      emoji:"🍱", label:"Meal Prepper",         desc:"Logged 10 weeks of meal prep",            category:"nutrition" },
  { id:"plant-week",     emoji:"🌱", label:"Plant Week",          desc:"Ate plant-based for 7 days",              category:"nutrition" },
  { id:"sugar-free",     emoji:"🚫", label:"Sugar Free",          desc:"Avoided added sugar for 14 days",         category:"nutrition" },
  { id:"macro-master",   emoji:"⚖️", label:"Macro Master",        desc:"Hit all 3 macro goals in a single day",   category:"nutrition" },
  { id:"barcode-10",     emoji:"📱", label:"Scanner",             desc:"Logged 10 foods via barcode scan",         category:"nutrition" },
  { id:"barcode-100",    emoji:"📊", label:"Data Logger",         desc:"Logged 100 foods via barcode scan",        category:"nutrition" },
  { id:"fasting",        emoji:"⏳", label:"Fasting Pro",         desc:"Completed a 24-hour fast",                category:"nutrition" },
  { id:"clean-30",       emoji:"🥦", label:"Clean 30",            desc:"Ate clean for 30 days straight",          category:"nutrition" },
  // Nutrition logging milestones (auto-awarded)
  { id:"first-nutrition-log",emoji:"🥗", label:"First Log",       desc:"Logged your first nutrition entry",       category:"nutrition" },
  { id:"nutrition-week", emoji:"📅", label:"Nutrition Week",      desc:"Logged nutrition 7 days in a row",        category:"nutrition" },
  { id:"nutrition-pro",  emoji:"🏅", label:"Nutrition Pro",       desc:"Hit macro goals 14 days in a row",        category:"nutrition" },
  { id:"nutrition-100",  emoji:"💪", label:"100 Nutrition Logs",  desc:"Logged nutrition 100 times",              category:"nutrition" },

  // ── CHALLENGES ────────────────────────────────────────────────────────────
  { id:"iron-will",      emoji:"🪖", label:"Iron Will",           desc:"Completed a 30-day challenge",            category:"challenges" },
  { id:"75-hard",        emoji:"🔩", label:"75 Hard",             desc:"Completed the 75 Hard program",           category:"challenges" },
  { id:"murph",          emoji:"🇺🇸", label:"Murph",             desc:"Completed the Murph workout",             category:"challenges" },
  { id:"spartan",        emoji:"🏔️", label:"Spartan",            desc:"Completed a Spartan Race",                category:"challenges" },
  { id:"tough-mudder",   emoji:"🪤", label:"Tough Mudder",        desc:"Completed a Tough Mudder",                category:"challenges" },
  { id:"crossfit-open",  emoji:"🏅", label:"CrossFit Open",       desc:"Competed in the CrossFit Open",           category:"challenges" },
  { id:"pushup-100",     emoji:"⬇️", label:"100 Push-Ups",       desc:"Did 100 push-ups in one session",         category:"challenges" },
  { id:"plank-5min",     emoji:"⏱️", label:"Plank Legend",       desc:"Held a plank for 5 minutes",              category:"challenges" },
  { id:"burpee-100",     emoji:"🌀", label:"Burpee Beast",        desc:"Completed 100 burpees in one session",    category:"challenges" },
  { id:"pullup-20",      emoji:"⬆️", label:"Pull-Up Pro",        desc:"Did 20 consecutive pull-ups",             category:"challenges" },

  // ── SOCIAL ────────────────────────────────────────────────────────────────
  { id:"first-post",     emoji:"📸", label:"First Post",          desc:"Made your first post on the feed",        category:"social" },
  { id:"10-posts",       emoji:"📷", label:"Content Creator",     desc:"Made 10 posts on the feed",               category:"social" },
  { id:"first-follower", emoji:"👥", label:"First Follower",      desc:"Got your first follower",                 category:"social" },
  { id:"100-followers",  emoji:"🌐", label:"Rising Star",         desc:"Reached 100 followers",                   category:"social" },
  { id:"group-member",   emoji:"🤝", label:"Group Member",        desc:"Joined your first group",                 category:"social" },
  { id:"group-leader",   emoji:"🎙️", label:"Group Leader",       desc:"Created a group",                         category:"social" },
  { id:"first-like",     emoji:"❤️", label:"Liked",              desc:"Received your first like",                category:"social" },
  { id:"motivator",      emoji:"🙌", label:"Motivator",           desc:"Had a post liked 50+ times",              category:"social" },

  // ── SPECIAL ───────────────────────────────────────────────────────────────
  { id:"veteran",        emoji:"🎖️", label:"Veteran",            desc:"US Military Service",                     category:"special" },
  { id:"first-gym",      emoji:"🏟️", label:"Gym Rat",            desc:"Checked into a gym for the first time",   category:"special" },
  { id:"coach",          emoji:"🎓", label:"Coach",               desc:"Became a certified fitness coach",        category:"special" },
  { id:"personal-trainer",emoji:"📋",label:"Personal Trainer",    desc:"Earned a personal training certification",category:"special" },
  { id:"transformation", emoji:"🦋", label:"Transformation",      desc:"Completed a 90-day body transformation",  category:"special" },
  { id:"comeback-story", emoji:"💫", label:"Comeback Story",      desc:"Returned from injury and hit a new PR",   category:"special" },
  { id:"birthday-workout",emoji:"🎂",label:"Birthday Grind",      desc:"Worked out on your birthday",             category:"special" },
  { id:"new-years",      emoji:"🎆", label:"New Year, New Me",    desc:"Logged a workout on January 1st",         category:"special" },
  { id:"holiday-hustle", emoji:"🎄", label:"Holiday Hustle",      desc:"Worked out on a major holiday",           category:"special" },
  { id:"collab",         emoji:"🤜", label:"Workout Partner",     desc:"Logged a workout with a friend",          category:"special" },
  { id:"outdoor-adventurer",emoji:"🧗",label:"Outdoor Adventurer",desc:"Completed a hike, climb, or outdoor adventure",category:"special" },
  { id:"sport-competitor",emoji:"🏆",label:"Competitor",          desc:"Competed in any athletic event",          category:"special" },
];

export type Badge = typeof BADGES[0];
